target:
- ind_recommended
continuous_cols:
- customer_digital_activity_02
- customer_profile_01
- customer_profile_02
- customer_profile_03
- customer_profile_04
- customer_spend_06
- customer_spend_07
- distance_05
categorical_cols:
- merchant_profile_01
date_columns: []
encode_date_columns: true
validation_split: 0.2
continuous_feature_transform: null
normalize_continuous_features: true
quantile_noise: 0
num_workers: 10
pin_memory: true
handle_unknown_categories: true
handle_missing_values: true
task: classification
head: LinearHead
head_config:
  layers: ''
  activation: ReLU
  dropout: 0.1
  use_batch_norm: false
  initialization: kaiming
embedding_dims: null
embedding_dropout: 0.0
batch_norm_continuous_input: true
learning_rate: 0.001
loss: CrossEntropyLoss
metrics:
- f1_score
- accuracy
metrics_prob_input:
- true
- false
metrics_params:
- num_classes: 2
- {}
target_range: null
virtual_batch_size: null
seed: 42
_module_src: models.category_embedding
_model_name: CategoryEmbeddingModel
_backbone_name: CategoryEmbeddingBackbone
_config_name: CategoryEmbeddingModelConfig
layers: 1024-512-512
activation: LeakyReLU
use_batch_norm: false
initialization: kaiming
dropout: 0.0
batch_size: 5210
data_aware_init_batch_size: 2000
fast_dev_run: false
max_epochs: 100
min_epochs: 1
max_time: null
accelerator: auto
devices: -1
devices_list: null
accumulate_grad_batches: 1
auto_lr_find: true
auto_select_gpus: true
check_val_every_n_epoch: 1
gradient_clip_val: 0.0
overfit_batches: 0.0
deterministic: false
profiler: null
early_stopping: valid_loss
early_stopping_min_delta: 0.001
early_stopping_mode: min
early_stopping_patience: 5
early_stopping_kwargs: {}
checkpoints: valid_loss
checkpoints_path: checkpoints
checkpoints_every_n_epochs: 1
checkpoints_name: null
checkpoints_mode: min
checkpoints_save_top_k: 5
checkpoints_kwargs: {}
load_best: true
track_grad_norm: -1
progress_bar: simple
precision: 32
trainer_kwargs:
  enable_progress_bar: true
project_name: AMEX
run_name: ind_recommended
exp_watch: gradients
log_target: tensorboard
log_logits: true
exp_log_freq: 100
optimizer: Adam
optimizer_params: {}
lr_scheduler: null
lr_scheduler_params: {}
lr_scheduler_monitor_metric: valid_loss
categorical_dim: 1
enable_checkpointing: true
